[package]
name = "jp2000"
version = "0.1.0"
authors = ["Iszak Bryan <38895+iszak@users.noreply.github.com>"]
edition = "2018"

[dependencies]
clap = {features=["derive"], version="4.5.41"}
env_logger = "0.11.8"

jp2 = { path = "../jp2" }
jpc = { path = "../jpc" }
jpxml = { path = "../jpxml" }
